INSERT INTO availability_stones (stockNumber, availability, shape, carat, color, clarity, cut, polish, lab, reportNumber, price, location)
VALUES
('ALV-RND-01', 'Available', 'ROUND', 0.5, 'F', 'VS1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-02', 'Available', 'ROUND', 0.5, 'G', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-03', 'Available', 'ROUND', 0.5, 'H', 'SI1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-04', 'Available', 'ROUND', 0.7, 'E', 'VVS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-05', 'Available', 'ROUND', 0.7, 'F', 'VS1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-06', 'Available', 'ROUND', 0.7, 'G', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-07', 'Available', 'ROUND', 0.7, 'H', 'SI1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-08', 'Available', 'ROUND', 0.9, 'F', 'VS1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-09', 'Available', 'ROUND', 0.9, 'G', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-10', 'Available', 'ROUND', 0.9, 'H', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-11', 'Available', 'ROUND', 1, 'D', 'VVS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-12', 'Available', 'ROUND', 1, 'E', 'VVS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-13', 'Available', 'ROUND', 1, 'F', 'VS1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-14', 'Available', 'ROUND', 1, 'G', 'VS1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-15', 'Available', 'ROUND', 1, 'G', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-16', 'Available', 'ROUND', 1, 'H', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-17', 'Available', 'ROUND', 1, 'H', 'SI1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-18', 'Available', 'ROUND', 1.25, 'F', 'VS1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-19', 'Available', 'ROUND', 1.25, 'G', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-20', 'Available', 'ROUND', 1.25, 'H', 'SI1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-21', 'Available', 'ROUND', 1.5, 'E', 'VVS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-22', 'Available', 'ROUND', 1.5, 'F', 'VS1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-23', 'Available', 'ROUND', 1.5, 'G', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-24', 'Available', 'ROUND', 1.5, 'H', 'SI1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-25', 'Available', 'ROUND', 2, 'F', 'VS1', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-26', 'Available', 'ROUND', 2, 'G', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-27', 'Available', 'ROUND', 2.5, 'G', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RND-28', 'Available', 'ROUND', 3, 'H', 'VS2', 'EX', 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-01', 'Available', 'OVAL', 0.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-02', 'Available', 'OVAL', 0.7, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-03', 'Available', 'OVAL', 0.7, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-04', 'Available', 'OVAL', 0.7, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-05', 'Available', 'OVAL', 0.9, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-06', 'Available', 'OVAL', 0.9, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-07', 'Available', 'OVAL', 0.9, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-08', 'Available', 'OVAL', 1, 'E', 'VVS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-09', 'Available', 'OVAL', 1, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-10', 'Available', 'OVAL', 1, 'G', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-11', 'Available', 'OVAL', 1, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-12', 'Available', 'OVAL', 1, 'H', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-13', 'Available', 'OVAL', 1, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-14', 'Available', 'OVAL', 1.25, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-15', 'Available', 'OVAL', 1.25, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-16', 'Available', 'OVAL', 1.25, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-17', 'Available', 'OVAL', 1.5, 'E', 'VVS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-18', 'Available', 'OVAL', 1.5, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-19', 'Available', 'OVAL', 1.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-20', 'Available', 'OVAL', 1.5, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-21', 'Available', 'OVAL', 2, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-22', 'Available', 'OVAL', 2, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-23', 'Available', 'OVAL', 2.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-OVL-24', 'Available', 'OVAL', 3, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-01', 'Available', 'PEAR', 0.7, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-02', 'Available', 'PEAR', 0.9, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-03', 'Available', 'PEAR', 1, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-04', 'Available', 'PEAR', 1, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-05', 'Available', 'PEAR', 1, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-06', 'Available', 'PEAR', 1.25, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-07', 'Available', 'PEAR', 1.5, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-08', 'Available', 'PEAR', 1.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-09', 'Available', 'PEAR', 1.5, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-10', 'Available', 'PEAR', 2, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-11', 'Available', 'PEAR', 2, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PER-12', 'Available', 'PEAR', 2.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-01', 'Available', 'EMERALD', 0.9, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-02', 'Available', 'EMERALD', 1, 'E', 'VVS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-03', 'Available', 'EMERALD', 1, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-04', 'Available', 'EMERALD', 1, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-05', 'Available', 'EMERALD', 1.25, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-06', 'Available', 'EMERALD', 1.5, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-07', 'Available', 'EMERALD', 1.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-08', 'Available', 'EMERALD', 1.5, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-09', 'Available', 'EMERALD', 2, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-EMD-10', 'Available', 'EMERALD', 2, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-CSH-01', 'Available', 'CUSHION', 0.9, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-CSH-02', 'Available', 'CUSHION', 1, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-CSH-03', 'Available', 'CUSHION', 1, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-CSH-04', 'Available', 'CUSHION', 1, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-CSH-05', 'Available', 'CUSHION', 1.5, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-CSH-06', 'Available', 'CUSHION', 1.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-CSH-07', 'Available', 'CUSHION', 2, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-CSH-08', 'Available', 'CUSHION', 2.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RAD-01', 'Available', 'RADIANT', 0.9, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RAD-02', 'Available', 'RADIANT', 1, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RAD-03', 'Available', 'RADIANT', 1, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RAD-04', 'Available', 'RADIANT', 1, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RAD-05', 'Available', 'RADIANT', 1.5, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RAD-06', 'Available', 'RADIANT', 1.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RAD-07', 'Available', 'RADIANT', 2, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-RAD-08', 'Available', 'RADIANT', 2, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PRN-01', 'Available', 'PRINCESS', 1, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PRN-02', 'Available', 'PRINCESS', 1, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PRN-03', 'Available', 'PRINCESS', 1, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PRN-04', 'Available', 'PRINCESS', 1.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-PRN-05', 'Available', 'PRINCESS', 2, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-MQS-01', 'Available', 'MARQUISE', 1, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-MQS-02', 'Available', 'MARQUISE', 1, 'H', 'SI1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-MQS-03', 'Available', 'MARQUISE', 1.5, 'F', 'VS1', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-MQS-04', 'Available', 'MARQUISE', 1.5, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India'),
('ALV-MQS-05', 'Available', 'MARQUISE', 2, 'G', 'VS2', NULL, 'EX', 'IGI', NULL, NULL, 'India')
ON DUPLICATE KEY UPDATE
  availability = VALUES(availability),
  shape = VALUES(shape),
  carat = VALUES(carat),
  color = VALUES(color),
  clarity = VALUES(clarity),
  cut = VALUES(cut),
  polish = VALUES(polish),
  lab = VALUES(lab),
  reportNumber = VALUES(reportNumber),
  price = VALUES(price),
  location = VALUES(location),
  importedAt = NOW();
