CREATE TABLE IF NOT EXISTS `jewellery_enquiries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`kind` enum('piece','consultation') NOT NULL DEFAULT 'piece',
	`pieceCode` varchar(20),
	`pieceName` varchar(180),
	`metal` varchar(40),
	`karat` varchar(10),
	`caratWeight` varchar(20),
	`ringSize` varchar(20),
	`contactName` varchar(180) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(80),
	`country` varchar(80),
	`preferredContact` enum('email','whatsapp','phone','video') NOT NULL DEFAULT 'email',
	`preferredTime` varchar(160),
	`budget` varchar(60),
	`message` text,
	`landingPage` varchar(300),
	`referrer` varchar(200),
	`alertStatus` enum('pending','sent','failed') NOT NULL DEFAULT 'pending',
	`alertError` text,
	`alertMessageId` varchar(160),
	`followUpStatus` enum('new','contacted','quoted','won','lost','on_hold') NOT NULL DEFAULT 'new',
	`ownerName` varchar(120),
	`internalNote` text,
	`lastActionAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jewellery_enquiries_id` PRIMARY KEY(`id`),
	KEY `jewellery_enquiries_created_idx` (`createdAt`),
	KEY `jewellery_enquiries_status_idx` (`followUpStatus`,`createdAt`)
);
