import { FormEvent, MouseEvent, useRef, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Menu, MoveRight, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import PublicMetadata from "@/components/PublicMetadata";
import { navigateToPublicAnchor, scrollToPublicAnchor, usePublicHashNavigation } from "@/lib/hashNavigation";

const heroImage = "/assets/alvora-hero-qc.webp";
const facetingImage = "/assets/alvora-cutting-faceting.webp";
const laserImage = "/assets/alvora-laser-calibration.webp";
const markImage = "/assets/alvora-faceted-a.webp";

type Variant = "fr" | "it" | "us";
type MarketCode = "FR" | "IT" | "US" | "CA";

type MarketContent = {
  market: Exclude<MarketCode, "CA">;
  lang: string;
  a11y: { skip: string; main: string; primaryNavigation: string; languageSelection: string; heroAlt: string; facetingAlt: string; laserAlt: string };
  nav: { production: string; specification: string; process: string; buyer: string; commission: string };
  hero: { eyebrow: string; title: string; copy: string; maker: string; index: string; footer: string; productionLink: string };
  heritage: { number: string; title: string; paragraphs: string[]; maker: string; numbersTitle: string; numbers: [string, string][] };
  production: { eyebrow: string; title: string; copy: string; cards: [string, string][]; caption: string };
  spec: { eyebrow: string; stamp: string; title: string; copy: string; cards: [string, string][]; lead: string; action: string };
  process: { eyebrow: string; title: string; copy: string; panels: [string, string, string][]; action: string; imageLabel: string };
  faq: { eyebrow: string; title: string; entries: [string, string][]; maker: string };
  brief: {
    eyebrow: string; title: string; copy: string; labels: { request: string; name: string; email: string; company: string; years: string; references: string; payment: string; note: string; requirements: string; country?: string };
    requestTypes: string[]; years: string[]; references: string[]; payment: string[]; requirementPlaceholder: string; submit: string; submitting: string; privacy: string; error: string; successSent: string; successRecorded: string;
  };
  credentials: { title: string; detail: string; items: [string, string][] };
  footer: { line: string; back: string; privacy: string; terms: string };
  northAmerica?: { eyebrow: string; title: string; copy: string; items: [string, string][]; note: string; countries: [string, string][] };
};

const referralLabelByVariant: Record<Variant, { label: string; placeholder: string }> = {
  fr: { label: "Introduit par un contact professionnel ? (facultatif)", placeholder: "Nom du contact qui vous a présenté" },
  it: { label: "Presentato da un contatto commerciale? (facoltativo)", placeholder: "Nome del contatto che vi ha presentato" },
  us: { label: "Introduced by a trade contact? (optional)", placeholder: "Name of the introducing contact" },
};

const availabilityTeaserCopyByVariant: Record<Variant, { eyebrow: string; title: string; copy: string; action: string; freshness: string; loading: string; empty: string }> = {
  fr: { eyebrow: "DISPONIBILITÉ DE PRODUCTION ACTUELLE", title: "À l’atelier, prêtes maintenant.", copy: "Consultez les pierres de production actuelles, avec leurs détails IGI vérifiables.", action: "Voir la disponibilité", freshness: "Dernière actualisation :", loading: "Vérification de la disponibilité actuelle…", empty: "La disponibilité actuelle apparaîtra ici après son actualisation." },
  it: { eyebrow: "DISPONIBILITÀ DI PRODUZIONE ATTUALE", title: "Dal banco, pronte ora.", copy: "Consultate le pietre di produzione attuali, con dettagli IGI verificabili.", action: "Vedi disponibilità", freshness: "Ultimo aggiornamento:", loading: "Verifica della disponibilità attuale…", empty: "La disponibilità attuale apparirà qui dopo il suo aggiornamento." },
  us: { eyebrow: "CURRENT PRODUCTION AVAILABILITY", title: "From the bench, ready now.", copy: "View current production stones with verifiable IGI detail.", action: "View availability", freshness: "Last refreshed:", loading: "Checking current availability…", empty: "Current availability will appear here after its next refresh." },
};

const availabilityCountLabelByVariant: Record<Variant, string> = {
  fr: "profils actuels",
  it: "profili attuali",
  us: "current profiles",
};

export const marketLandingContent: Record<Variant, MarketContent> = {
  fr: {
    market: "FR", lang: "fr",
    a11y: { skip: "Aller au contenu principal", main: "Contenu principal", primaryNavigation: "Navigation principale", languageSelection: "Sélection de la langue", heroAlt: "Un diamant fini est inspecté à la loupe pendant le contrôle qualité.", facetingAlt: "Un outil d’atelier taille et facette un diamant.", laserAlt: "Une station laser effectue l’identification finale à l’établi." },
    nav: { production: "Notre production", specification: "Fabrication sur mesure", process: "Notre méthode", buyer: "Disponibilité", commission: "Demander une fabrication" },
    hero: { eyebrow: "Fabricant de diamants synthétiques, Surat", title: "Des diamants synthétiques fabriqués selon un standard auquel les acheteurs exigeants peuvent se fier.", copy: "Alvora fabrique des diamants synthétiques certifiés et calibrés pour les équipes joaillières qui exigent une maîtrise de chaque dimension.", maker: "Vous achetez directement aux établis — sans usine dissimulée derrière nous.", index: "Fabrication à Surat, directe à votre établi", footer: "Certifiés / Calibrés / Fabriqués à Surat", productionLink: "Voir notre production" },
    heritage: { number: "02 — FABRIQUÉ À SURAT", title: "Fabriqué à Surat, par nos établis.", paragraphs: ["Alvora est ancrée dans le pôle de taille et de polissage de Surat, au plus près du travail, des outils et des personnes qui maîtrisent la fabrication.", "Chaque diamant synthétique expédié est calibré selon notre standard : taille Excellent/Ideal, sans fluorescence ni BGM. Il est laser-inscrit par IGI et validé dans la base IGI avant expédition.", "Nous fabriquons selon vos spécifications et pouvons reprendre les pierres que nous avons réalisées."], maker: "Taillés, calibrés et certifiés IGI par notre propre équipe.", numbersTitle: "En chiffres", numbers: [["25+", "ans d’expérience"], ["10 000+", "pierres expédiées"], ["100%", "standard IGI sur chaque pierre"], ["DIRECT", "prix direct établi"]] },
    production: { eyebrow: "03 — NOTRE PRODUCTION", title: "Ce que nous fabriquons.", copy: "Des diamants synthétiques certifiés, taillés, calibrés et finis pour un travail fiable à l’établi.", cards: [["Pierres certifiées", "La certification est intégrée à la fabrication, jamais ajoutée après coup."], ["Profils calibrés", "Dimensions et ratios répétables lorsque le serti fixe déjà les exigences."], ["Parcelles assorties", "Des assortiments harmonisés pour la cohérence de teinte, les proportions et la lecture de la pièce finie."]], caption: "FACETTAGE / EN COURS · SURAT / IND" },
    spec: { eyebrow: "04 — FABRICATION SUR MESURE", stamp: "SPÉC. 05–10 JOURS", title: "Fabriqué selon votre cahier des charges.", copy: "Transmettez les exigences de votre programme joaillier ; nous fabriquons la pierre selon les dimensions, le ratio et la finition attendus.", cards: [["Taille & calibration sur mesure", "Forme, dimensions exactes, ratios et finition sont réalisés selon le cahier des charges."], ["Agencements pour la fabrication", "Parcelles calibrées et agencements assortis pour les joailliers et les sertissages répétables."], ["Reprise au sein de la maison", "Recoupe, repolissage et reprise des pierres fabriquées par Alvora, avec continuité de connaissance." ]], lead: "Délai habituel pour une fabrication sur spécification : 5–10 jours ouvrés", action: "Demander une fabrication sur mesure" },
    process: { eyebrow: "05 — NOTRE MÉTHODE", title: "Une fabrication claire. Des conditions concrètes.", copy: "Nous commençons par les spécifications et restons responsables de la pierre après la sortie de nos établis.", panels: [["Paiement", "Pensé pour les joailliers actifs.", "Nous travaillons avec des joailliers et ateliers établis sur des conditions commerciales souples et négociées. La première commande confirme la fabrication ; les comptes récurrents évoluent vers des conditions convenues après vérifications de crédit et de références."], ["Fabrication assurée", "Réparer ou remplacer.", "Chaque diamant synthétique est vérifié par rapport à son certificat avant expédition. Dans le cas rare d’un écart de spécification, d’un éclat ou d’un problème de fabrication, la pierre revient à nos établis. Nous réparons ou remplaçons et la réexpédions."]], action: "Commencer un brief de fabrication", imageLabel: "INSCRIPTION LASER / IDENTIFICATION / CONTRÔLE FINAL" },
    faq: { eyebrow: "06 — QUESTIONS", title: "Les questions utiles.", entries: [["Quelles sont vos conditions de paiement ?", "Nous travaillons avec des joailliers et ateliers établis sur des conditions commerciales souples et négociées. Une première commande confirme la fabrication ; les comptes récurrents évoluent vers des conditions convenues après vérifications de crédit et de références."], ["Que se passe-t-il si une pierre nécessite une correction ?", "Chaque diamant synthétique est vérifié par rapport à son certificat avant expédition. Si une pierre nécessite une correction, elle revient à nos établis. Nous la réparons ou la remplaçons et la réexpédions."], ["Que peut-on préciser dans une fabrication sur mesure ?", "La forme, les dimensions exactes, les ratios, la finition, les exigences de parcelle et le calendrier peuvent être décrits dans le brief de fabrication."], ["Pouvez-vous assortir des pierres pour un agencement de fabrication ?", "Oui. Nous préparons des agencements assortis et des parcelles calibrées autour des proportions et de la cohérence visuelle requises."], ["Une pierre peut-elle être reprise après fabrication ?", "Nous pouvons évaluer les besoins de recoupe, repolissage et reprise pour les pierres fabriquées par Alvora, avec les informations de production initiales à portée de main."]], maker: "Chaque pierre expédiée est une pierre que nous avons fabriquée." },
    brief: { eyebrow: "07 — BRIEF DE FABRICATION", title: "Demander une fabrication.", copy: "Décrivez le programme, le profil ou les caractéristiques dont vous avez besoin. Nous reviendrons vers vous avec les détails de production utiles.", labels: { request: "Type de demande", name: "Votre nom", email: "E-mail professionnel", company: "Entreprise / atelier", years: "Années d’activité", references: "Références commerciales disponibles sur demande", payment: "Approche de paiement préférée pour une première commande", note: "Ces éléments servent uniquement à déterminer l’approche de compte adaptée à votre demande.", requirements: "Que devons-nous fabriquer ?" }, requestTypes: ["Série de fabrication", "Sur mesure / selon spécification", "Agencement assorti / parcelle calibrée", "Reprise d’une pierre Alvora"], years: ["Moins de 2 ans", "2–5 ans", "5–10 ans", "10 ans et plus"], references: ["Oui", "Non"], payment: ["Prépaiement sur proforma", "Conditions commerciales convenues après vérification de crédit", "Ouvert à la discussion"], requirementPlaceholder: "Forme, dimensions, ratios, finition, quantité, calendrier ou tout élément déjà défini à votre établi.", submit: "Envoyer le brief", submitting: "Enregistrement du brief…", privacy: "Nous utilisons ces informations uniquement pour comprendre la fabrication demandée.", error: "Votre brief n’a pas pu être enregistré. Veuillez réessayer ou contacter Alvora directement.", successSent: "Merci. Votre brief de fabrication a été enregistré et transmis à l’équipe Alvora.", successRecorded: "Merci. Votre brief de fabrication a été enregistré en toute sécurité pour l’équipe Alvora." },
    credentials: { title: "Documentation & vérification", detail: "pour chaque commande confirmée", items: [["CERT", "Liens de certificat affichés uniquement lorsqu’une destination officielle IGI ou GIA correspondante est disponible."], ["SPEC", "Spécification, référence de certificat et détails d’expédition confirmés par écrit pour chaque commande."], ["DOC", "Documents d’expédition préparés pour la destination et l’accord de livraison confirmés."], ["INS", "Itinéraire d’expédition et confirmation d’assurance fournis avec l’envoi confirmé."], ["FR", "Terminologie publique française : convention « diamant de synthèse » appliquée."]] },
    footer: { line: "Fabrication de diamants synthétiques\nSurat, Inde", back: "Retour en haut", privacy: "Confidentialité", terms: "Conditions de commerce" },
  },
  it: {
    market: "IT", lang: "it",
    a11y: { skip: "Vai al contenuto principale", main: "Contenuto principale", primaryNavigation: "Navigazione principale", languageSelection: "Selezione della lingua", heroAlt: "Un diamante finito viene ispezionato con una lente durante il controllo qualità.", facetingAlt: "Uno strumento da laboratorio taglia e sfaccetta un diamante.", laserAlt: "Una stazione laser completa l’identificazione finale al banco." },
    nav: { production: "La nostra produzione", specification: "Su specifica", process: "Come lavoriamo", buyer: "Disponibilità", commission: "Commissiona una lavorazione" },
    hero: { eyebrow: "Produttori di diamanti sintetici, Surat", title: "Diamanti sintetici realizzati secondo uno standard su cui gli acquirenti più esigenti possono contare.", copy: "Alvora produce diamanti sintetici certificati e calibrati per team di gioielleria che richiedono controllo in ogni dimensione.", maker: "Acquistate direttamente dal banco — non c’è uno stabilimento dietro di noi da aggirare.", index: "Produzione a Surat, diretta al vostro banco", footer: "Certificati / Calibrati / Realizzati a Surat", productionLink: "Scoprite la nostra produzione" },
    heritage: { number: "02 — REALIZZATO A SURAT", title: "Realizzato a Surat, dai nostri banchi.", paragraphs: ["Alvora nasce nel distretto di taglio e lucidatura di Surat, vicino al lavoro, agli strumenti e alle persone che conoscono la lavorazione.", "Ogni diamante sintetico spedito è calibrato sul nostro standard: taglio Excellent/Ideal, senza fluorescenza né BGM. È inciso al laser da IGI e convalidato nel database IGI prima della spedizione.", "Realizziamo su specifica e possiamo rielaborare le pietre che abbiamo prodotto."], maker: "Tagliati, calibrati e certificati IGI dal nostro team.", numbersTitle: "In numeri", numbers: [["25+", "anni di esperienza"], ["10.000+", "pietre spedite"], ["100%", "standard IGI su ogni pietra"], ["DIRETTO", "prezzi dal banco"]] },
    production: { eyebrow: "03 — LA NOSTRA PRODUZIONE", title: "Ciò che realizziamo.", copy: "Diamanti sintetici certificati, tagliati, calibrati e rifiniti per un lavoro affidabile al banco.", cards: [["Pietre certificate", "Certificazione gestita come parte della lavorazione, non come un’aggiunta successiva."], ["Profili calibrati", "Dimensioni e rapporti ripetibili quando l’incastonatura stabilisce già i parametri."], ["Lotti abbinati", "Layout abbinati per coerenza tonale, proporzioni e lettura del pezzo finito."]], caption: "SFACCETTATURA / IN LAVORAZIONE · SURAT / IND" },
    spec: { eyebrow: "04 — SU SPECIFICA", stamp: "SPEC. 05–10 GIORNI", title: "Realizzati secondo la vostra specifica.", copy: "Inviate la specifica necessaria al vostro programma di gioielleria e realizzeremo la pietra secondo dimensioni, rapporti e finitura richiesti.", cards: [["Taglio e calibrazione personalizzati", "Forma, dimensioni esatte, rapporti e finitura vengono lavorati secondo la scheda tecnica del cliente."], ["Layout per la produzione", "Layout abbinati e lotti calibrati per gioiellieri produttivi e montature ripetibili."], ["Rielaborazione interna", "Ritaglio, rilucidatura e rielaborazione delle pietre prodotte da Alvora, con continuità delle informazioni di produzione."]], lead: "Tempi tipici per una lavorazione su specifica: 5–10 giorni lavorativi", action: "Commissiona una lavorazione su specifica" },
    process: { eyebrow: "05 — COME LAVORIAMO", title: "Una lavorazione chiara. Condizioni pratiche.", copy: "Partiamo dalla specifica e restiamo responsabili della pietra dopo che la lavorazione finita lascia i nostri banchi.", panels: [["Pagamento", "Per gioiellieri operativi.", "Lavoriamo con gioiellieri e atelier affermati con condizioni commerciali flessibili e negoziate. I primi ordini confermano la lavorazione; gli account continuativi passano a condizioni concordate dopo verifiche di credito e referenze."], ["Lavorazione garantita", "Riparare o sostituire.", "Ogni diamante sintetico viene verificato rispetto al certificato prima della spedizione. Nel raro caso di una difformità di specifica, una scheggiatura o un problema di lavorazione, la pietra torna ai nostri banchi. Ripariamo o sostituiamo e la rispediamo."]], action: "Avviare un brief di produzione", imageLabel: "ISCRIZIONE LASER / IDENTIFICAZIONE / CONTROLLO FINALE" },
    faq: { eyebrow: "06 — FAQ", title: "Le domande utili.", entries: [["Quali sono le vostre condizioni di pagamento?", "Lavoriamo con gioiellieri e atelier affermati con condizioni commerciali flessibili e negoziate. Un primo ordine conferma la lavorazione; gli account continuativi passano a condizioni concordate dopo verifiche di credito e referenze."], ["Cosa succede se una pietra necessita una correzione?", "Ogni diamante sintetico viene verificato rispetto al certificato prima della spedizione. Se una pietra necessita una correzione, torna ai nostri banchi. La ripariamo o sostituiamo e la rispediamo."], ["Cosa posso specificare in una lavorazione personalizzata?", "Forma, dimensioni esatte, rapporti, finitura, esigenze di lotto e tempistiche possono essere inseriti nel brief di produzione."], ["Potete abbinare pietre per un layout produttivo?", "Sì. Prepariamo layout abbinati e lotti calibrati attorno alle proporzioni e alla coerenza visiva richieste dal pezzo finito."], ["Una pietra può essere rielaborata dopo la produzione?", "Possiamo valutare taglio, rilucidatura e rielaborazione delle pietre prodotte da Alvora, con le informazioni originali di produzione a portata di mano."]], maker: "Ogni pietra che spediamo è una pietra che abbiamo realizzato." },
    brief: { eyebrow: "07 — BRIEF DI PRODUZIONE", title: "Commissionate una lavorazione.", copy: "Indicate il programma, il profilo o la specifica necessaria. Risponderemo con i dettagli pratici di produzione.", labels: { request: "Tipo di richiesta", name: "Il vostro nome", email: "E-mail di lavoro", company: "Azienda / atelier", years: "Anni di attività", references: "Referenze commerciali disponibili su richiesta", payment: "Approccio di pagamento preferito per un primo ordine", note: "Questi dati sono utilizzati solo per valutare l’approccio di account appropriato alla richiesta.", requirements: "Che cosa occorre realizzare?" }, requestTypes: ["Serie di produzione", "Personalizzato / su specifica", "Layout abbinato / lotto calibrato", "Rielaborazione di una pietra Alvora"], years: ["Meno di 2", "2–5", "5–10", "10+"], references: ["Sì", "No"], payment: ["Prepagato su proforma", "Termini commerciali concordati dopo verifica del credito", "Aperti alla discussione"], requirementPlaceholder: "Forma, dimensioni, rapporti, finitura, quantità, tempistiche o qualsiasi elemento già definito al vostro banco.", submit: "Invia il brief", submitting: "Registrazione del brief…", privacy: "Usiamo queste informazioni solo per comprendere la lavorazione necessaria.", error: "Il brief non è stato registrato. Riprovate o contattate direttamente Alvora.", successSent: "Grazie. Il vostro brief di produzione è stato registrato e inviato al team Alvora.", successRecorded: "Grazie. Il vostro brief di produzione è stato registrato in sicurezza per il team Alvora." },
    credentials: { title: "Documentazione & verifica", detail: "per ogni ordine confermato", items: [["CERT", "Collegamenti ai certificati mostrati solo quando è disponibile una destinazione ufficiale IGI o GIA corrispondente."], ["SPEC", "Specifica, riferimento del certificato e dettagli di spedizione confermati per iscritto per ogni ordine."], ["DOC", "Documenti di spedizione preparati per la destinazione e l’accordo di consegna confermati."], ["INS", "Itinerario di spedizione e conferma assicurativa forniti con la spedizione confermata."], ["IT", "Dettagli commerciali e documentazione confermati con il preventivo o la conferma d’ordine."]] },
    footer: { line: "Produzione di diamanti sintetici\nSurat, India", back: "Torna all’inizio", privacy: "Informativa privacy", terms: "Condizioni di commercio" },
  },
  us: {
    market: "US", lang: "en",
    a11y: { skip: "Skip to main content", main: "Main content", primaryNavigation: "Primary navigation", languageSelection: "Language selection", heroAlt: "A finished stone inspected through a jeweller’s loupe during quality control.", facetingAlt: "A workshop tool cuts and facets a stone.", laserAlt: "A laser station completes final identification at a production bench." },
    nav: { production: "Our production", specification: "Made to specification", process: "How we work", buyer: "Availability", commission: "Commission a make" },
    hero: { eyebrow: "Lab-Grown Diamond Manufacturers, Surat", title: "Diamonds made to a standard exacting North American buyers can rely on.", copy: "Alvora manufactures certified, calibrated lab-grown diamonds for jewellery teams that need control in every dimension.", maker: "You’re buying from the bench — there’s no factory behind us to go around.", index: "Surat manufacturing, direct to your bench", footer: "Certified / Calibrated / Made in Surat", productionLink: "See our production" },
    heritage: { number: "02 — MADE IN SURAT", title: "Made in Surat, by our benches.", paragraphs: ["Alvora is built inside Surat’s cutting-and-polishing cluster: close to the work, the tools and the people who understand the make.", "Every stone we ship is calibrated to our standard make: Excellent/Ideal cut, no fluorescence, no BGM. It is IGI laser-inscribed and validated against the IGI database before dispatch.", "We make to a specification, and we can rework what we have made."], maker: "Cut, calibrated and IGI-certified by our own team.", numbersTitle: "By the numbers", numbers: [["25+", "years of experience"], ["10,000+", "stones dispatched"], ["100%", "IGI standard on every stone"], ["DIRECT", "from-bench pricing"]] },
    production: { eyebrow: "03 — OUR PRODUCTION", title: "What we make.", copy: "Certified lab-grown diamonds, cut, calibrated and finished for reliable work at the bench.", cards: [["Certified stones", "Production with certification handled as part of the make, not as an afterthought."], ["Calibrated profiles", "Repeatable dimensions and ratios for programmes where the setting already sets the terms."], ["Matched parcels", "Layouts matched for tonal consistency, proportion, and the way a finished piece must read."]], caption: "FACETING / IN PROCESS · SURAT / IND" },
    spec: { eyebrow: "04 — MADE TO SPECIFICATION", stamp: "SPEC 05–10 DAYS", title: "Made to your specification.", copy: "Send the specification your jewellery programme needs, and we make the diamond to meet it.", cards: [["Custom cut & calibration", "Shape, exact dimensions, ratios and finish are worked to the buyer’s specification sheet."], ["Layouts made for manufacture", "Matched layouts and calibrated parcels for manufacturing jewellers and repeatable settings."], ["Rework within the house", "Recut, repolish and rework of stones we have made, with continuity of production knowledge."]], lead: "Typical lead time for a spec make: 5–10 working days", action: "Commission a spec make" },
    process: { eyebrow: "05 — HOW WE WORK", title: "A clear make. Practical terms.", copy: "We begin with the specification and stay accountable to the stone after the finished make leaves our benches.", panels: [["Payment", "Built for working jewellers.", "We work with established jewellers and ateliers on flexible, negotiated trade terms. First orders confirm the make; ongoing accounts move to agreed terms after credit and reference checks. We work beyond a prepaid model."], ["Assured make", "Repair or replace.", "Every stone is verified against its certificate before dispatch. In the rare case a piece needs correction — a spec mismatch, a chip, a make issue — it goes back to our benches. We repair or replace and return it."]], action: "Start a production brief", imageLabel: "LASER INSCRIPTION / IDENTIFICATION / FINAL CHECK" },
    faq: { eyebrow: "06 — FAQ", title: "The useful questions.", entries: [["What are your payment terms?", "We work with established jewellers and ateliers on flexible, negotiated trade terms. A first order confirms the make; ongoing accounts move to agreed terms after credit and reference checks."], ["What if a stone needs correction?", "Every stone is verified against its certificate before dispatch. If a piece needs correction, it goes back to our benches. We repair or replace and return it."], ["What can I specify in a custom make?", "Shape, exact dimensions, ratios, finish, parcel requirements and timing can all be placed in the production brief."], ["Can you match stones for a manufacturing layout?", "Yes. Matched layouts and calibrated parcels are prepared around the proportions and visual consistency your finished piece requires."], ["Can a stone be reworked after it is made?", "We can assess recut, repolish and rework requirements for stones made by Alvora, with the original production information close at hand."]], maker: "Every stone we ship is one we made." },
    brief: { eyebrow: "07 — PRODUCTION BRIEF", title: "Commission a make.", copy: "Tell us the programme, profile, or specification you need. We will return with the practical production detail.", labels: { request: "Request type", name: "Your name", email: "Work email", company: "Company / workshop", years: "Years trading", references: "Trade references available on request", payment: "Preferred payment approach for a first order", note: "These details are used only to assess the right account approach for your enquiry.", requirements: "What needs to be made?", country: "Country served" }, requestTypes: ["Production run", "Custom / made-to-spec.", "Matched layout / calibrated parcel", "Rework of an Alvora stone"], years: ["Under 2", "2–5", "5–10", "10+"], references: ["Yes", "No"], payment: ["Prepaid on proforma", "Agreed trade terms subject to credit check", "Open to discussion"], requirementPlaceholder: "Shape, dimensions, ratios, finish, quantity, timing or anything already decided at your bench.", submit: "Send production brief", submitting: "Recording brief…", privacy: "We use this information only to understand the make you require.", error: "Your brief could not be recorded. Please try again, or contact Alvora directly.", successSent: "Thank you. Your production brief has been recorded and sent to the Alvora team.", successRecorded: "Thank you. Your production brief has been safely recorded for the Alvora team." },
    credentials: { title: "Documentation & verification", detail: "for each confirmed order", items: [["CERT", "Certificate links appear only where a matching official IGI or GIA destination is present."], ["SPEC", "Specification, certificate reference and dispatch details are confirmed in writing for each order."], ["DOC", "Shipment documentation is prepared against the confirmed destination and delivery arrangement."], ["NA", "US and Canada delivery details are confirmed with the relevant quote or order confirmation."], ["INS", "Dispatch route and insurance confirmation are provided with the confirmed shipment."]] },
    footer: { line: "Lab-grown diamond manufacturing\nSurat, India", back: "Back to top", privacy: "Privacy", terms: "Terms of trade" },
    northAmerica: { eyebrow: "NORTH AMERICA / CLEAR DELIVERY", title: "Serving US & Canada.", copy: "A direct manufacturing relationship should arrive with a clear commercial path, not a customs question at the last minute.", items: [["United States", "US buyers receive tariff-inclusive quotes, so there are no customs surprises within the confirmed quotation scope."], ["Canada", "Loose polished synthetic diamonds classified under HS 7104 carry 0% MFN duty in Canada; destination taxes and final classification remain shipment-specific."], ["Dispatch", "Shipments are cleared through DHL or FedEx Express, fully insured, and normally arrive in 2–4 business days."]], note: "Classification, destination taxes, and delivery timing are confirmed for each shipment. No fluctuating tariff percentage is published here.", countries: [["United States", "US"], ["Canada", "CA"]] },
  },
};

function LanguageSwitcher({ current, label }: { current: Variant; label: string }) {
  return <nav className="language-switcher" aria-label={label}><a href="/" className={current === "us" ? "is-active" : ""}>EN</a><a href="/fr" className={current === "fr" ? "is-active" : ""} lang="fr">FR</a><a href="/it" className={current === "it" ? "is-active" : ""} lang="it">IT</a></nav>;
}

export default function MarketLanding({ variant }: { variant: Variant }) {
  const content = marketLandingContent[variant];
  const referralLabel = referralLabelByVariant[variant];
  const [menuOpen, setMenuOpen] = useState(false);
  const [requestType, setRequestType] = useState(content.brief.requestTypes[0]);
  const [submissionState, setSubmissionState] = useState<"idle" | "sending" | "sent" | "saved" | "error">("idle");
  const formRef = useRef<HTMLFormElement>(null);
  usePublicHashNavigation();
  const availabilitySummary = trpc.availability.summary.useQuery();
  const availabilityTeaser = availabilityTeaserCopyByVariant[variant];
  const availabilityHref = variant === "fr" ? "/fr/availability" : variant === "it" ? "/it/availability" : "/availability";
  const submitProductionBrief = trpc.productionBrief.submit.useMutation({ onMutate: () => setSubmissionState("sending"), onSuccess: (result) => { setSubmissionState(result.alertStatus === "sent" ? "sent" : "saved"); formRef.current?.reset(); setRequestType(content.brief.requestTypes[0]); }, onError: () => setSubmissionState("error") });

  const openBrief = (type = content.brief.requestTypes[0]) => {
    setRequestType(type); setSubmissionState("idle"); setMenuOpen(false);
    window.requestAnimationFrame(() => scrollToPublicAnchor("#production-brief"));
  };

  const handlePublicAnchor = (event: MouseEvent<HTMLDivElement>) => {
    const link = (event.target as Element | null)?.closest<HTMLAnchorElement>('a[href^="#"]');
    const hash = link?.getAttribute("href");
    if (!link || !hash || link.classList.contains("skip-link") || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
    if (navigateToPublicAnchor(hash)) event.preventDefault();
  };

  const submitBrief = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const values = new FormData(event.currentTarget);
    const countryMarket = variant === "us" ? String(values.get("country")) as MarketCode : content.market;
    const yearsValues = ["Under 2", "2–5", "5–10", "10+"] as const;
    const paymentValues = ["Prepaid on proforma", "Agreed trade terms subject to credit check", "Open to discussion"] as const;
    setSubmissionState("idle");
    submitProductionBrief.mutate({
      requestType: String(values.get("request_type")), market: countryMarket, website: String(values.get("_website") || ""), contactName: String(values.get("name")).trim(), email: String(values.get("email")).trim(), company: String(values.get("company") || "").trim() || undefined,
      yearsTrading: yearsValues[Number(values.get("years_trading"))] ?? "2–5", tradeReferencesAvailable: String(values.get("trade_references")) === "No" ? "No" : "Yes", preferredPaymentApproach: paymentValues[Number(values.get("preferred_payment_approach"))] ?? "Open to discussion", referrerName: String(values.get("referrer_name") || "").trim() || undefined, brief: String(values.get("brief")).trim(),
    });
  };

  return <div id="top" className="site-shell" lang={content.lang} onClickCapture={handlePublicAnchor}><PublicMetadata locale={variant} /><a className="skip-link" href="#main-content">{content.a11y.skip}</a>
    <header className="site-header" aria-label={content.a11y.primaryNavigation}>
      <a className="brand" href="#top" aria-label="Alvora home"><img className="brand-mark" src={markImage} alt="" /><span className="brand-name">ALVORA</span></a>
      <nav className="desktop-nav" aria-label="Main navigation"><a href="#production">{content.nav.production}</a><a href="#made-to-spec">{content.nav.specification}</a><a href="#how-we-work">{content.nav.process}</a><a href={availabilityHref}>{content.nav.buyer}</a></nav>
      <LanguageSwitcher current={variant} label={content.a11y.languageSelection} />
      <button className="header-cta" type="button" onClick={() => openBrief()}>{content.nav.commission}<ArrowUpRight size={15} strokeWidth={1.7} /></button>
      <button className="menu-toggle" type="button" aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} onClick={() => setMenuOpen((open) => !open)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button>
      {menuOpen && <div className="mobile-nav"><a href="#production" onClick={() => setMenuOpen(false)}>{content.nav.production}</a><a href="#made-to-spec" onClick={() => setMenuOpen(false)}>{content.nav.specification}</a><a href="#how-we-work" onClick={() => setMenuOpen(false)}>{content.nav.process}</a><a href={availabilityHref} onClick={() => setMenuOpen(false)}>{content.nav.buyer}</a><LanguageSwitcher current={variant} label={content.a11y.languageSelection} /><button type="button" onClick={() => openBrief()}>{content.nav.commission}<ArrowUpRight size={16} /></button></div>}
    </header>

    <main id="main-content" tabIndex={-1} aria-label={content.a11y.main}>
      <section className="hero" aria-labelledby="hero-title"><img className="hero-image" src={heroImage} alt={content.a11y.heroAlt} /><div className="hero-scrim" /><div className="hero-rule hero-rule-a" /><div className="hero-rule hero-rule-b" /><div className="hero-content"><p className="eyebrow eyebrow-bright"><span />{content.hero.eyebrow}</p><h1 id="hero-title">{content.hero.title}</h1><p className="hero-copy">{content.hero.copy}</p><p className="hero-maker-line">{content.hero.maker}</p><div className="hero-actions"><button className="button button-signal" type="button" onClick={() => openBrief()}>{content.nav.commission}<ArrowDownRight size={18} strokeWidth={1.6} /></button><a className="text-link text-link-light" href="#production">{content.hero.productionLink}<MoveRight size={17} strokeWidth={1.5} /></a></div></div><div className="hero-index"><span>01</span><p>{content.hero.index}</p></div><div className="hero-footer"><span>{content.hero.footer}</span><span className="scroll-note">Scroll <ArrowDownRight size={14} /></span></div></section>

      {content.northAmerica && <section className="market-panel-section" aria-labelledby="north-america-title"><div><p className="eyebrow eyebrow-bright"><span />{content.northAmerica.eyebrow}</p><h2 id="north-america-title">{content.northAmerica.title}</h2><p>{content.northAmerica.copy}</p></div><div className="market-panel-list">{content.northAmerica.items.map(([label, description]) => <article key={label}><span>{label}</span><p>{description}</p></article>)}</div><p className="market-panel-note">{content.northAmerica.note}</p></section>}

      <section className="heritage-section" id="heritage" aria-labelledby="heritage-title"><p className="section-number">{content.heritage.number}</p><div className="heritage-content"><h2 id="heritage-title">{content.heritage.title}</h2><div className="heritage-prose">{content.heritage.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p className="heritage-maker-line">{content.heritage.maker}</p></div></div><div className="by-numbers"><p>{content.heritage.numbersTitle}</p><div className="numbers-strip">{content.heritage.numbers.map(([value, label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div></div></section>

      <section className="production-section" id="production" aria-labelledby="production-title"><div className="section-heading production-heading"><div><p className="eyebrow"><span />{content.production.eyebrow}</p><h2 id="production-title">{content.production.title}</h2></div><p>{content.production.copy}</p></div><div className="production-grid"><article className="production-image-card"><img src={facetingImage} alt={content.a11y.facetingAlt} /><div className="image-caption"><span>{content.production.caption}</span></div></article><div className="production-list">{content.production.cards.map(([title, description], index) => <article key={title}><span className="list-index">0{index + 1}</span><div><h3>{title}</h3><p>{description}</p></div><ArrowUpRight size={18} strokeWidth={1.4} /></article>)}</div></div><section className="production-live" aria-labelledby="production-live-title"><div className="production-live-heading"><div><p className="eyebrow"><span />{availabilityTeaser.eyebrow}</p><h3 id="production-live-title">{availabilityTeaser.title}</h3><p>{availabilityTeaser.copy}</p></div><a className="button button-outline" href={availabilityHref}>{availabilityTeaser.action}<MoveRight size={16} /></a></div>{availabilitySummary.data?.import && <p className="production-live-freshness">{availabilityTeaser.freshness} {new Date(availabilitySummary.data.import.activatedAt).toLocaleString()}</p>}{availabilitySummary.isLoading ? <p className="production-live-empty">{availabilityTeaser.loading}</p> : availabilitySummary.data?.total ? <div className="production-profile-grid">{availabilitySummary.data.byShape.slice(0, 6).map((profile) => <article key={profile.shape}><span>{profile.shape}</span><strong>{profile.count}</strong><p>{profile.count} {availabilityCountLabelByVariant[variant]}</p></article>)}</div> : <p className="production-live-empty">{availabilityTeaser.empty}</p>}</section></section>

      <section className="spec-section" id="made-to-spec" aria-labelledby="spec-title"><div className="spec-masthead"><p className="eyebrow eyebrow-bright"><span />{content.spec.eyebrow}</p><p className="spec-stamp">{content.spec.stamp}</p></div><div className="spec-lead"><h2 id="spec-title">{content.spec.title}</h2><p>{content.spec.copy}</p></div><div className="spec-grid">{content.spec.cards.map(([title, description], index) => <article key={title}><span className="spec-number">{String.fromCharCode(65 + index)}</span><h3>{title}</h3><p>{description}</p></article>)}</div><div className="spec-action-row"><p><span className="status-dot" />{content.spec.lead}</p><button className="button button-outline" type="button" onClick={() => openBrief(content.brief.requestTypes[1])}>{content.spec.action}<ArrowDownRight size={18} /></button></div></section>

      <section className="process-section" id="how-we-work" aria-labelledby="process-title"><div className="process-image-wrap"><img src={laserImage} alt={content.a11y.laserAlt} /><div className="process-image-overlay" /><p className="process-image-label">{content.process.imageLabel}</p></div><div className="process-content"><p className="eyebrow"><span />{content.process.eyebrow}</p><h2 id="process-title">{content.process.title}</h2><p>{content.process.copy}</p><div className="commercial-panels">{content.process.panels.map(([label, title, description]) => <article key={label}><span>{label}</span><h3>{title}</h3><p>{description}</p></article>)}</div><a className="text-link" href="#production-brief">{content.process.action}<MoveRight size={17} strokeWidth={1.5} /></a></div></section>

      <section className="faq-section" id="faq" aria-labelledby="faq-title"><div className="faq-heading"><p className="eyebrow"><span />{content.faq.eyebrow}</p><h2 id="faq-title">{content.faq.title}</h2></div><div className="faq-content">{content.faq.entries.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}<p className="faq-maker-line">{content.faq.maker}</p></div></section>

      <section className="brief-section" id="production-brief" aria-labelledby="brief-title">
        <div className="brief-intro"><p className="eyebrow eyebrow-bright"><span />{content.brief.eyebrow}</p><h2 id="brief-title">{content.brief.title}</h2><p>{content.brief.copy}</p><div className="brief-aside"><span>ALVORA / SURAT</span><span>MANUFACTURING ENQUIRY</span></div></div>
        <form ref={formRef} className="brief-form" onSubmit={submitBrief}>
          <div className="honeypot-field" aria-hidden="true"><label>Website<input name="_website" type="text" tabIndex={-1} autoComplete="off" /></label></div>
          <label><span>{content.brief.labels.request}</span><select name="request_type" value={requestType} onChange={(event) => setRequestType(event.target.value)}>{content.brief.requestTypes.map((type) => <option key={type}>{type}</option>)}</select></label>
          <div className="form-row"><label><span>{content.brief.labels.name}</span><input name="name" type="text" autoComplete="name" minLength={2} maxLength={180} required placeholder={content.brief.labels.name} /></label><label><span>{content.brief.labels.email}</span><input name="email" type="email" autoComplete="email" inputMode="email" autoCapitalize="none" spellCheck={false} maxLength={320} required placeholder="name@company.com" /></label></div>
          <label><span>{content.brief.labels.company}</span><input name="company" type="text" autoComplete="organization" maxLength={180} placeholder={content.brief.labels.company} /></label>
          {content.northAmerica && <label><span>{content.brief.labels.country}</span><select name="country" autoComplete="country" defaultValue="US">{content.northAmerica.countries.map(([label, value]) => <option key={value} value={value}>{label}</option>)}</select></label>}
          <div className="form-qualification-grid"><label><span>{content.brief.labels.years}</span><select name="years_trading" defaultValue="1">{content.brief.years.map((label, index) => <option key={label} value={index}>{label}</option>)}</select></label><label><span>{content.brief.labels.references}</span><select name="trade_references" defaultValue="Yes">{content.brief.references.map((label, index) => <option key={label} value={index === 0 ? "Yes" : "No"}>{label}</option>)}</select></label></div>
          <label><span>{content.brief.labels.payment}</span><select name="preferred_payment_approach" defaultValue="1">{content.brief.payment.map((label, index) => <option key={label} value={index}>{label}</option>)}</select></label>
          <label><span>{referralLabel.label}</span><input name="referrer_name" type="text" maxLength={180} placeholder={referralLabel.placeholder} /></label>
          <p className="form-qualification-note">{content.brief.labels.note}</p>
          <label><span>{content.brief.labels.requirements}</span><textarea name="brief" minLength={10} maxLength={5000} required rows={5} placeholder={content.brief.requirementPlaceholder} /></label>
          <div className="form-submit-row"><button className="button button-signal" type="submit" disabled={submitProductionBrief.isPending}>{submitProductionBrief.isPending ? content.brief.submitting : <>{content.brief.submit}<ArrowUpRight size={18} /></>}</button><p>{content.brief.privacy}</p></div>
          {submissionState !== "idle" && <p className={`form-confirmation form-confirmation-${submissionState}`} role={submissionState === "error" ? "alert" : "status"} aria-live="polite">{submissionState === "sending" ? content.brief.submitting : submissionState === "sent" ? content.brief.successSent : submissionState === "saved" ? content.brief.successRecorded : content.brief.error}</p>}
        </form>
      </section>
    </main>

    <section className="credentials-strip" aria-label={content.credentials.title}><p className="credentials-title">{content.credentials.title}<span>{content.credentials.detail}</span></p><div className="credentials-list">{content.credentials.items.map(([mark, detail]) => <p key={mark}><b>{mark}</b><span>{detail}</span></p>)}</div></section>
    <footer className="site-footer"><div className="footer-brand"><img className="brand-mark" src={markImage} alt="" /><span className="brand-name">ALVORA</span></div><p>{content.footer.line}</p><nav className="footer-legal" aria-label="Information"><a href="/privacy">{content.footer.privacy}</a><a href="/terms">{content.footer.terms}</a></nav><a href="#top">{content.footer.back}<ArrowUpRight size={15} /></a><nav className="footer-specialty" aria-label="Products and services"><a href="/calibrated-diamond-layouts">Calibrated Layouts</a><a href="/matched-pair-diamonds">Matched Pairs</a><a href="/custom-cut-diamonds">Custom Cut</a><a href="/melee-diamonds">Melee Diamonds</a><a href="/certifications">Certifications</a><a href="/about">About</a><a href="/for-jewelry-brands">For Jewellery Brands</a><a href="/request-a-quote">Request a Quote</a></nav></footer>
  </div>;
}
