/**
 * Typed access to the Alvora jewellery catalogue.
 *
 * catalog.json is generated by scripts/jewellery/build-catalog.mjs from the
 * partner launch shortlist. It carries Alvora names only; partner sourcing
 * lives server-side in server/data/jewellery-sourcing.json.
 */
import rawCatalog from "./catalog.json";

export type JewelleryCategory = "ring" | "band" | "earrings" | "pendant";
export type JewelleryCollection = "engagement-rings" | "rings" | "wedding-bands" | "earrings" | "pendants" | "antique-cuts" | "coloured-stones";
export type MetalColour = "yellow" | "white" | "rose";

export type JewelleryImage = {
  src: string;
  thumb: string;
  width: number | null;
  height: number | null;
};

export type JewelleryPiece = {
  code: string;
  slug: string;
  name: string;
  collectionName: string;
  wave: "A" | "B";
  /** On the site: launch-list piece allowed by data/jewellery/launch.json. */
  live: boolean;
  category: JewelleryCategory;
  collections: JewelleryCollection[];
  shape: string | null;
  shapeLabel: string | null;
  style: string;
  styleLabel: string;
  stoneColour: string;
  stoneColourLabel: string | null;
  karats: string[];
  metalColours: MetalColour[];
  caratRange: [number, number] | null;
  fromPriceUsd: number | null;
  description: string;
  /** Editorial tags from data/jewellery/pieces.json, e.g. "dutch-marquise". */
  tags: string[];
  featuredScore: number;
  addedOn: string | null;
  images: JewelleryImage[];
};

export const ALL_PIECES = rawCatalog as JewelleryPiece[];

/** Pieces on the site (retail and trade), as set by data/jewellery/launch.json. */
export const PUBLIC_PIECES = ALL_PIECES.filter((piece) => piece.live);

export function findPublicPiece(slug: string): JewelleryPiece | undefined {
  return PUBLIC_PIECES.find((piece) => piece.slug === slug);
}

export function findPieceByCode(code: string): JewelleryPiece | undefined {
  return ALL_PIECES.find((piece) => piece.code === code);
}

export function formatFromPrice(piece: Pick<JewelleryPiece, "fromPriceUsd">): string {
  if (piece.fromPriceUsd == null) return "Price on request";
  return `From ${new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(piece.fromPriceUsd)}`;
}

export const SHAPE_ORDER = ["oval", "round", "emerald", "pear", "marquise", "radiant", "cushion", "elongated-cushion", "old-mine", "asscher", "hexagon", "princess"] as const;
