/**
 * Typed access to the Alvora jewellery catalogue.
 *
 * catalog.json is generated by scripts/jewellery/build-catalog.mjs from the
 * partner launch shortlist. It carries Alvora names only; partner sourcing
 * lives server-side in server/data/jewellery-sourcing.json.
 */
import rawCatalog from "./catalog.json";
import { fromPriceInr } from "./pricing";
import { formatMoney, type CurrencyCode } from "./currency";

export type JewelleryCategory = "ring" | "band" | "earrings" | "pendant";
export type JewelleryCollection = "engagement-rings" | "rings" | "wedding-bands" | "earrings" | "pendants" | "antique-cuts" | "coloured-stones";
export type MetalColour = "yellow" | "white" | "rose";

export type JewelleryImage = {
  src: string;
  thumb: string;
  width: number | null;
  height: number | null;
  /** Overrides the piece-name alt text (used for shared, non-product photos). */
  alt?: string;
};

/** Shown last in every product gallery: loose diamonds beside their grading reports. */
export const GRADING_REPORT_IMAGE: JewelleryImage = {
  src: "/assets/jewellery/shared/grading-report.webp",
  thumb: "/assets/jewellery/shared/grading-report-600.webp",
  width: 1400,
  height: 1400,
  alt: "Loose lab-grown diamonds beside their laboratory grading reports",
};

export type JewelleryPiece = {
  code: string;
  slug: string;
  name: string;
  collectionName: string;
  wave: "A" | "B";
  /** On the site: launch-list piece allowed by data/jewellery/launch.json. */
  live: boolean;
  category: JewelleryCategory;
  collections: JewelleryCollection[];
  shape: string | null;
  shapeLabel: string | null;
  style: string;
  styleLabel: string;
  stoneColour: string;
  stoneColourLabel: string | null;
  karats: string[];
  metalColours: MetalColour[];
  caratRange: [number, number] | null;
  /** Partner-derived USD price; internal only. Public prices come from pricing.ts. */
  fromPriceUsd: number | null;
  description: string;
  /** Editorial tags from data/jewellery/pieces.json, e.g. "dutch-marquise". */
  tags: string[];
  featuredScore: number;
  addedOn: string | null;
  images: JewelleryImage[];
};

export const ALL_PIECES = rawCatalog as JewelleryPiece[];

/**
 * Pieces on the site (retail and trade): chosen by data/jewellery/launch.json,
 * and shown once they have at least one photo.
 */
export function isShown(piece: Pick<JewelleryPiece, "live" | "images">) {
  return piece.live && piece.images.length > 0;
}

export const PUBLIC_PIECES = ALL_PIECES.filter(isShown);

export function findPublicPiece(slug: string): JewelleryPiece | undefined {
  return PUBLIC_PIECES.find((piece) => piece.slug === slug);
}

export function findPieceByCode(code: string): JewelleryPiece | undefined {
  return ALL_PIECES.find((piece) => piece.code === code);
}

/** Public "From" price (rupee table in pricing.ts, shown in `currency`), or "Price on request". */
export function formatFromPrice(piece: Pick<JewelleryPiece, "category" | "collections">, currency: CurrencyCode = "INR"): string {
  const price = fromPriceInr(piece);
  return price == null ? "Price on request" : `From ${formatMoney(price, currency)}`;
}

export const SHAPE_ORDER = ["oval", "round", "emerald", "pear", "marquise", "radiant", "cushion", "elongated-cushion", "old-mine", "asscher", "hexagon", "princess"] as const;
